server:
  port: 4397

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ncqa_dev
    username: ubuntu
    password: xuxiao123
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: 139.199.170.177
    port: 6379
    password: xuxiao123


  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
logging:
  file: C:/javaLog/logging.log
  path: C:/

mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/*.xml
  config-location: classpath:config/mybatis/mybatis-config.xml


